import { Geist, Geist_Mono } from "next/font/google";

import type { Metadata } from "next";

import { Toaster } from "@/components/ui/sonner";

import { ScaleProvider } from "@/contexts/scale-context";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ScaleProvider>{children}</ScaleProvider>
        <Toaster />
      </body>
    </html>
  );
}
